### ISSUE TITLE
Allow options to configure the ports for Test Kitchen and Observability framework in the installer

### ISSUE THREAD

**Issue by jagatsingh** [DataKitchen/data-observability-installer#26]
Allow install on customised ports via environment variables or some other configuration for the ports.

**Comment by diogodk** [comment]
Hello @jagatsingh , the observability installer supports overriding the default port by using `python3 dk-installer.py obs expose --port <number>` and for testgen with `python3 dk-installer.py tg install --port <number>` . We'll add this note to the README file in this repository.

If using the helm charts to install observability, the default 8082 port can be overridden by the `values.yml` file or helm install `--set` option, by setting `observability_ui.service.nodePort` . 

We do not support environment variables for setting these values. 

Does this answer your questions and needs?
