### ISSUE TITLE
Ubuntu docker-compose extra_hosts: "host.docker.internal:host-gateway" does not work

### ISSUE THREAD

**Issue by jagatsingh** [DataKitchen/data-observability-installer#27]
Error

`urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=8082): Max retries exceeded with url: /api/observability/v1/projects/1b3706e1-8b1a-4234-94c7-f23e5e7e9550/journeys?search=Nightly%20Exports (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9e90728ec0>, 'Connection to host.docker.internal timed out. (connect timeout=None)'))`

**Comment by diogodk** [comment]
Hello @jagatsingh, the mapping works if you run the `python3 dk-installer.py obs expose` [command](https://github.com/DataKitchen/data-observability-installer?tab=readme-ov-file#bind-http-ports-to-host-machine). Like your other issue we will improve the documentation to note this requirement, if we can't find an alternative mapping or docker networking configuration that does not require the command.
